### PR TITLE
Enable PCRE2 instead of PCRE1

### PR DESCRIPTION
**Pull request by denji**
I checked locally, everything works.

### CODE REVIEW

**Comment by hardware** [comment]
Build failed on Cirrus CI. Do you check the build locally ?

**Comment by denji** [comment]
I checked locally, everything works.

Cirrus-CI: `Error: UNAUTHORIZED: "authentication required"`

```
Usage:
  executor [flags]
Flags:
      --azure-container-registry-config string   Path to the file containing Azure container registry configuration information.
      --build-arg multi-arg type                 This flag allows you to pass in ARG values at build time. Set it repeatedly for multiple values.
  -c, --context string                           Path to the dockerfile build context. (default "/workspace/")
  -d, --destination multi-arg type               Registry the final image should be pushed to. Set it repeatedly for multiple destinations. (default )
  -f, --dockerfile string                        Path to the dockerfile to be built. (default "Dockerfile")
      --force                                    Force building outside of a container
  -h, --help                                     help for executor
      --insecure                                 Push to insecure registry using plain HTTP
      --no-push                                  Do not push the image to the registry
      --reproducible                             Strip timestamps out of the image to make it reproducible
      --single-snapshot                          Take a single snapshot at the end of the build.
      --skip-tls-verify                          Push to insecure registry ignoring TLS verify
      --snapshotMode string                      Change the file attributes inspected during snapshotting (default "full")
      --tarPath string                           Path to save the image in as a tarball instead of pushing
      --target string                            Set the target build stage to build
  -v, --verbosity string                         Log level (debug, info, warn, error, fatal, panic (default "info")
```

**Comment by hardware** [comment]
> I checked locally, everything works.

On my side too, and works now with Cirrus-CI, probably related to a temporary issue.

> I use PCRE2-JIT without PCREv1 and with the removed Hyperscan module.
https://github.com/hardware/mailserver/issues/295#issuecomment-418963564

No issue detected with PCRE2 used on your mail server ? I will do some tests next week, if everything is good, I will merge your PR.

**Comment by denji** [comment]
@hardware /ping

**Comment by denji** [comment]
https://github.com/mailsrv-hw/debian-mail-overlay/commit/5b5655dce57d92e466f92976dd3c8d849ee5ef48

**Pull request closed without merging**
